#ifndef LINEAR_FEEDBACK_CONTROLLER__HANDLE_ROS_VERSIONS_HPP_
#define LINEAR_FEEDBACK_CONTROLLER__HANDLE_ROS_VERSIONS_HPP_

#define CONTROLLER_INTERFACE_VERSION_AT_LEAST(major, minor, patch) \
  ((CONTROLLER_INTERFACE_MAJOR_VERSION > (major)) ||               \
   (CONTROLLER_INTERFACE_MAJOR_VERSION == (major) &&               \
    CONTROLLER_INTERFACE_MINOR_VERSION > (minor)) ||               \
   (CONTROLLER_INTERFACE_MAJOR_VERSION == (major) &&               \
    CONTROLLER_INTERFACE_MINOR_VERSION == (minor) &&               \
    CONTROLLER_INTERFACE_PATCH_VERSION >= (patch)))

#endif  //  LINEAR_FEEDBACK_CONTROLLER__HANDLE_ROS_VERSIONS_HPP_
